name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name : Print Greeting
        run : |
              echo "This is my first job start"
              pwd
      - name : Say Good Bye
        run : |
              echo "This is my first job end"
              echo "end"
